baseURL = 'http://hibizibi.github.io/'
languageCode = 'en-us'
title = 'The place of all learning'

# Change the default theme to be use when building the site with Hugo
theme = "learn"

[params]
description = "Hibizibi"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

